<a href="https://colab.research.google.com/github/FauzanNR/dicoding-data-analysis/blob/main/Dicoding_Data_analyst.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
mkdir dicoding_data_analysis

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [76]:
customer_df = pd.read_csv("https://raw.githubusercontent.com/dicodingacademy/dicoding_dataset/main/DicodingCollection/customers.csv")
customer_df.name = "customer"
customer_df.head()

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country
0,1,fulan 1,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia
1,2,fulan 2,Prefer not to say,69,8327 Kirlin SummitApt. 461,8223,New Zacharyfort,South Australia,Australia
2,3,fulan 3,Prefer not to say,59,269 Gemma SummitSuite 109,5661,Aliburgh,Australian Capital Territory,Australia
3,4,fulan 4,Prefer not to say,67,743 Bailey GroveSuite 141,1729,South Justinhaven,Queensland,Australia
4,5,fulan 5,Prefer not to say,30,48 Hyatt ManorSuite 375,4032,Griffithsshire,Queensland,Australia

In [3]:
orders_df = pd.read_csv("https://raw.githubusercontent.com/dicodingacademy/dicoding_dataset/main/DicodingCollection/orders.csv")
orders_df.name = "orders"
orders_df.head()

   order_id  customer_id  payment order_date delivery_date
0         1           64    30811  2021-8-30    2021-09-24
1         2          473    50490   2021-2-3    2021-02-13
2         3          774    46763  2021-10-8    2021-11-03
3         4          433    39782   2021-5-6    2021-05-19
4         5          441    14719  2021-3-23    2021-03-24

In [4]:
product_df = pd.read_csv("https://raw.githubusercontent.com/dicodingacademy/dicoding_dataset/main/DicodingCollection/products.csv")
product_df.name = "product"
product_df.head()

,product_id,product_type,product_name,size,colour,price,quantity,description
0,0,Shirt,Oxford Cloth,XS,red,114,66,"A red coloured, XS sized, Oxford Cloth Shirt"
1,1,Shirt,Oxford Cloth,S,red,114,53,"A red coloured, S sized, Oxford Cloth Shirt"
2,2,Shirt,Oxford Cloth,M,red,114,54,"A red coloured, M sized, Oxford Cloth Shirt"
3,3,Shirt,Oxford Cloth,L,red,114,69,"A red coloured, L sized, Oxford Cloth Shirt"
4,4,Shirt,Oxford Cloth,XL,red,114,47,"A red coloured, XL sized, Oxford Cloth Shirt"

In [33]:
sales_df = pd.read_csv("https://raw.githubusercontent.com/dicodingacademy/dicoding_dataset/main/DicodingCollection/sales.csv")
sales_df.name = "sales"
sales_df.head()

   sales_id  order_id  product_id  price_per_unit  quantity  total_price
0         0         1         218             106         2        212.0
1         1         1         481             118         1        118.0
2         2         1           2              96         3        288.0
3         3         1        1002             106         2        212.0
4         4         1         691             113         3        339.0

#Data Assessment

In [6]:
# prompt: create array cointaining this variable and don't generate the import function:
# customer_df
# orders_df
# product_df
# sales_df

dataframes = [customer_df, orders_df, product_df, sales_df]

for df in dataframes:

   print(f"---data {df.name} info---")
   print(df.info())

   print("---data missing---")
   print( df.isna().sum())

   print("---data duplicated---")
   print(df.duplicated().sum())

   print("---data Desc---")
   print(df.describe())

---data customer info---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1007 entries, 0 to 1006
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    1007 non-null   int64
 1   customer_name  1007 non-null   object
 2   gender         989 non-null    object
 3   age            1007 non-null   int64
 4   home_address   1007 non-null   object
 5   zip_code       1007 non-null   int64
 6   city           1007 non-null   object
 7   state          1007 non-null   object
 8   country        1007 non-null   object
dtypes: int64(3), object(6)
memory usage: 70.9+ KB
None
---data missing---
customer_id       0
customer_name     0
gender           18
age               0
home_address      0
zip_code          0
city              0
state             0
country           0
dtype: int64
---data duplicated---
6
---data Desc---
       customer_id          age     zip_code
count  1007.000000  1007.000000  1007.000000
mean    501.726912    50.929494  5012.538232
std     288.673238    30.516299  2885.836112
min       1.000000    20.000000     2.000000
25%     252.500000    34.000000  2403.500000
50%     502.000000    50.000000  5087.000000
75%     751.500000    65.000000  7493.500000
max    1000.000000   700.000000  9998.000000
---data orders info---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1000 non-null   int64
 1   customer_id    1000 non-null   int64
 2   payment        1000 non-null   int64
 3   order_date     1000 non-null   object
 4   delivery_date  1000 non-null   object
dtypes: int64(3), object(2)
memory usage: 39.2+ KB
None
---data missing---
order_id         0
customer_id      0
payment          0
order_date       0
delivery_date    0
dtype: int64
---data duplicated---
0
---data Desc---
          order_id  customer_id       payment
count  1000.000000  1000.000000   1000.000000
mean    500.500000   506.640000  33972.936000
std     288.819436   277.115502  14451.609047
min       1.000000     1.000000  10043.000000
25%     250.750000   275.250000  21329.250000
50%     500.500000   515.000000  33697.500000
75%     750.250000   737.250000  46249.000000
max    1000.000000  1000.000000  59910.000000
---data product info---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1266 entries, 0 to 1265
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    1266 non-null   int64
 1   product_type  1266 non-null   object
 2   product_name  1266 non-null   object
 3   size          1266 non-null   object
 4   colour        1266 non-null   object
 5   price         1266 non-null   int64
 6   quantity      1266 non-null   int64
 7   description   1266 non-null   object
dtypes: int64(3), object(5)
memory usage: 79.2+ KB
None
---data missing---
product_id      0
product_type    0
product_name    0
size            0
colour          0
price           0
quantity        0
description     0
dtype: int64
---data duplicated---
6
---data Desc---
        product_id        price     quantity
count  1266.000000  1266.000000  1266.000000
mean    627.926540   105.812006    60.138231
std     363.971586     9.715611    11.682791
min       0.000000    90.000000    40.000000
25%     313.250000    95.250000    50.000000
50%     626.500000   109.000000    60.000000
75%     942.750000   114.000000    70.000000
max    1259.000000   119.000000    80.000000
---data sales info---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sales_id        5000 non-null   int64
 1   order_id        5000 non-null   int64
 2   product_id      5000 non-null   int64
 3   price_per_unit  5000 non-null   int64
 4   quantity        5000 non-null   int64
 5   total_price     4981 non-null   float64
dtypes: float64(1), int64(5)
memory usage: 234.5 KB
None
---data missing---
sales_id           0
order_id           0
product_id         0
price_per_unit     0
quantity           0
total_price       19
dtype: int64
---data duplicated---
0
---data Desc---
          sales_id     order_id   product_id  price_per_unit    quantity  \
count  5000.000000  5000.000000  5000.000000     5000.000000  5000.00000
mean   2499.500000   503.038200   634.053200      103.501600     1.99240
std    1443.520003   285.964418   363.255794        9.195004     0.80751
min       0.000000     1.000000     1.000000       90.000000     1.00000
25%    1249.750000   258.000000   323.000000       95.000000     1.00000
50%    2499.500000   504.500000   635.000000      102.000000     2.00000
75%    3749.250000   749.000000   951.000000      112.000000     3.00000
max    4999.000000   999.000000  1259.000000      119.000000     3.00000

       total_price
count  4981.000000
mean    206.307368
std      86.352449
min      90.000000
25%     112.000000
50%     204.000000
75%     285.000000
max     357.000000

#Data Cleaning

In [77]:
#Duplicated Data
for df in dataframes:
   df.drop_duplicates(inplace=True)

for df in dataframes:
   print(f"---data {df.name} info---")
   print(df.duplicated())

---data customer info---
0       False
1       False
2       False
3       False
4       False
        ...
1002    False
1003    False
1004    False
1005    False
1006    False
Length: 1000, dtype: bool
---data orders info---
0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool
---data product info---
0       False
1       False
2       False
3       False
4       False
        ...
1261    False
1262    False
1263    False
1264    False
1265    False
Length: 1260, dtype: bool
---data sales info---
0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Length: 5000, dtype: bool

In [78]:
#Missing Data

for df in dataframes:
   print(f"---data {df.name} info---")
   print(df.isna().sum())

---data customer info---
customer_id      0
customer_name    0
gender           0
age              0
home_address     0
zip_code         0
city             0
state            0
country          0
dtype: int64
---data orders info---
order_id         0
customer_id      0
payment          0
order_date       0
delivery_date    0
dtype: int64
---data product info---
product_id      0
product_type    0
product_name    0
size            0
colour          0
price           0
quantity        0
description     0
dtype: int64
---data sales info---
sales_id          0
order_id          0
product_id        0
price_per_unit    0
quantity          0
total_price       0
dtype: int64

In [79]:
#Customer Missing values
print(customer_df.gender.value_counts())
customer_df.gender.fillna(value="Prefer not to say", inplace=True)
print(customer_df.gender.isna())

gender
Prefer not to say    731
Male                 143
Female               115
Name: count, dtype: int64
0       False
1       False
2       False
3       False
4       False
        ...
1002    False
1003    False
1004    False
1005    False
1006    False
Name: gender, Length: 1007, dtype: bool

<ipython-input-79-02e5f476f4d1>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  customer_df.gender.fillna(value="Prefer not to say", inplace=True)

In [41]:
#Salse missing value

print(sales_df.total_price.isna().sum())
sales_df.total_price.fillna(value=sales_df.price_per_unit * sales_df.quantity, inplace=True)

19

In [42]:
print(sales_df.total_price.isna().sum())

0

In [84]:
#Inacurate Data
for ages in customer_df.age:
  if ages == customer_df.age.max():
    print(ages)

80
80
80
80
80
80
80
80
80
80
80
80
80
80
80

In [81]:
customer_df.age.replace(customer_df.age.max(), 70, inplace=True)

<ipython-input-81-787ef619ba59>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  customer_df.age.replace(customer_df.age.max(), 70, inplace=True)

In [83]:
customer_df.age.replace({customer_df.age.max(): 50}, inplace=True)

<ipython-input-83-23675fc89238>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  customer_df.age.replace({customer_df.age.max(): 50}, inplace=True)